# Generated by Django 6.0.5 on 2026-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='plate_number',
            field=models.CharField(max_length=50),
        ),
    ]
