# Generated by Django 6.0.5 on 2026-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
