# Generated by Django 6.0.5 on 2026-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_cancelled_by_alter_ride_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='destination',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
