# Generated by Django 6.0.5 on 2026-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
